
export const YDMessageEvents = {
    VIDEO_OPEN: 'VIDEO_OPEN',
    VIDEO_CLOSE: 'VIDEO_CLOSE',
    AUDIO_OPEN: 'AUDIO_OPEN',
    AUDIO_CLOSE: 'AUDIO_CLOSE',
    TALK_OPEN: 'TALK_OPEN',
    TALK_CLOSE: 'TALK_CLOSE',
    DATA: 'DATA',

    PLAYBACK_OPEN: 'PLAYBACK_OPEN',
    PLAYBACK_CLOSE: 'PLAYBACK_CLOSE',
    PLAYBACK_END: 'PLAYBACK_END',
    PLAYBACK_PAUSE: 'PLAYBACK_PAUSE',
    PLAYBACK_RESUME: 'PLAYBACK_RESUME',
    PLAYBACK_CHANGE: 'PLAYBACK_CHANGE',
    QUERY_VIDEO: 'QUERY_VIDEO',

    PTZ_ACTION: 'PTZ_ACTION',
}